/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:26dcb93b-ec9e-42a4-9742-01951544eaf3",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_lz9bdO6ew",
    "aws_user_pools_web_client_id": "1patn56p3ll9a262v9he4cdgp5",
    "oauth": {},
    "aws_user_files_s3_bucket": "leadsmanagementsyste5f2137295da5409ca3e2cf685e5230955-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://s2silnsjzvb55bfjvpfyxx7ouu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-ivvpegxgc5ah7pgu45pg4undsq"
};


export default awsmobile;
